version: "3.9"

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/templates:/etc/nginx/templates:ro
      - ./nginx/ssl:/etc/ssl:ro
    env_file:
      - ./.env.nginx
    depends_on:
      - app

  app:
    build:
      context: .
      target: production
      dockerfile: Dockerfile
    env_file:
      - .env