# .github/workflows/bot-ci.yml

name: Bot CI Pipeline

on:
  push:
    paths:
      - "bot/**"
  # pull_request:
  #   paths:
  #     - "bot/**"

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
    with:
      app_path: "bot"

  test:
    uses: ./.github/workflows/test.yml
    with:
      app_path: "bot"

  build-push:
    needs: [lint, test]
    # needs: [lint]
    uses: ./.github/workflows/build-push.yml
    with:
      app_name: "bot"
      context: "./bot"
      dockerfile: "./bot/Dockerfile"
