---
name: CI Pipeline

on: 
  pull_request:
  push:

jobs:
  ci:
    uses: TogetherCrew/operations/.github/workflows/ci.yml@main
    secrets:
      CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
