# .github/workflows/hivemind-adapter-ci.yml

name: Hivemind Adapter CI Pipeline

on:
  push:
    paths:
      - "hivemind-adapter/**"
  pull_request:
    paths:
      - "hivemind-adapter/**"

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
    with:
      app_path: "./hivemind-adapter"

  test:
    uses: ./.github/workflows/test.yml
    with:
      app_path: "./hivemind-adapter"
      node_version: "20"
      cache_dependency_path: "./hivemind-adapter/package-lock.json"

  build-push:
    needs: [lint, test]
    uses: ./.github/workflows/build-push.yml
    with:
      app_name: "hivemind-adapter"
      context: "./hivemind-adapter"
      dockerfile: "./hivemind-adapter/Dockerfile"
