# .github/workflows/lint.yml

name: Lint Workflow

on:
  workflow_call:
    inputs:
      app_path:
        description: 'Path to the application directory'
        required: true
        type: string
      linter_configs:
        description: 'Additional linter configurations'
        required: false
        type: mapping

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Linter
        uses: super-linter/super-linter@v5.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_WORKSPACE: ${{ github.workspace }}/${{ inputs.app_path }}
          TYPESCRIPT_DEFAULT_STYLE: prettier
          ${{ toJson(inputs.linter_configs) }}
