# .github/workflows/test.yml
name: Test Workflow

on:
  workflow_call:
    inputs:
      app_path:
        description: "Path to the application directory"
        required: true
        type: string

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker compose -f ${{ inputs.app_path }}/docker-compose.test.yml up --exit-code-from app
